import { ResumeTemplate, ResumeData, TemplateId } from '../../../types/resume';
import { 
  ALEX_MORGAN_PROFILE, 
  getSampleDataForTemplate, 
  INITIAL_USER_RESUME_DATA 
} from './sampleProfiles';

export const ALL_TEMPLATES: ResumeTemplate[] = [
  // 1. ATS / Professional
  {
    id: 'ats-professional',
    name: 'ATS Professional',
    category: 'ATS / Professional',
    filterCategory: 'ats',
    description: 'Gold standard single-column ATS format with high-contrast headers and optimal machine parseability.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'Software Engineering, IT, Finance, Graduate Roles',
    tags: ['ATS', 'Single Column', 'High Compatibility', 'Standard'],
    accentDefault: 'slate',
  },
  {
    id: 'ats-classic',
    name: 'ATS Classic',
    category: 'ATS / Professional',
    filterCategory: 'ats',
    description: 'Traditional formal serif typography with crisp horizontal border rules and conservative structure.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'Corporate, Banking, Law, Academic & Traditional Industries',
    tags: ['ATS', 'Classic Serif', 'Corporate', 'Formal'],
    accentDefault: 'charcoal',
  },
  {
    id: 'ats-executive',
    name: 'ATS Executive',
    category: 'ATS / Professional',
    filterCategory: 'ats',
    description: 'Authoritative layout with double-rule section accents and prominent executive summary styling.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'Senior Engineers, Tech Leads, Engineering Managers, Directors',
    tags: ['ATS', 'Executive', 'Leadership', 'Clean'],
    accentDefault: 'navy',
  },
  {
    id: 'ats-one-column',
    name: 'ATS One Column',
    category: 'ATS / Professional',
    filterCategory: 'ats',
    description: 'Minimalist high-density single column with zero decorative noise for 100% parse success.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page',
    layoutType: 'Compact Single Column',
    bestFor: 'Strict Automated Enterprise Parsers (Workday, Taleo, Greenhouse)',
    tags: ['ATS', 'Ultra Clean', 'Minimalist', 'Dense'],
    accentDefault: 'slate',
  },

  // 2. Software / Technology
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    category: 'Software / Technology',
    filterCategory: 'tech',
    description: 'Prioritizes Technical Skills and Flagship Projects upfront for fast engineering manager screening.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Software Engineers, Full Stack, Backend & Frontend Developers',
    tags: ['Tech', 'Projects First', 'Code Focus', 'GitHub Links'],
    accentDefault: 'slate',
  },
  {
    id: 'modern-developer',
    name: 'Modern Developer',
    category: 'Software / Technology',
    filterCategory: 'tech',
    description: 'Developer-centric aesthetic featuring monospace technology badges, dark slate accents, and stack pills.',
    atsFriendly: 'Parser optimized',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Open Source Contributors, DevOps, Cloud Architects, Web Devs',
    tags: ['Tech', 'Monospace', 'Modern Dev', 'Terminal Vibe'],
    accentDefault: 'emerald',
  },
  {
    id: 'competitive-programmer',
    name: 'Competitive Programmer',
    category: 'Software / Technology',
    filterCategory: 'tech',
    description: 'Engineered for algorithmists, contest medalists, and systems engineers with contest ratings & algorithmic problem solving stats.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page',
    layoutType: 'Header Split',
    bestFor: 'Competitive Programmers, Quant Systems, Algorithm Specialists, Core SWE',
    tags: ['Tech', 'Algorithms', 'Codeforces', 'LeetCode', 'Low Latency'],
    accentDefault: 'emerald',
  },
  {
    id: 'tech-professional',
    name: 'Tech Professional',
    category: 'Software / Technology',
    filterCategory: 'tech',
    description: 'Polished tech leadership presentation with clean pill tags and structured technical accomplishments.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'Systems Engineers, Staff Engineers, Cloud Practitioners',
    tags: ['Tech', 'Pill Tags', 'Modern', 'Clean'],
    accentDefault: 'navy',
  },
  {
    id: 'engineering-minimal',
    name: 'Engineering Minimal',
    category: 'Software / Technology',
    filterCategory: 'tech',
    description: 'Strict engineering discipline layout with compact grid for tools and high-impact action bullets.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page',
    layoutType: 'Compact Single Column',
    bestFor: 'Computer Science Graduates, Algorithms Engineers, Embedded Systems',
    tags: ['Tech', 'Minimal', 'Engineering', 'Compact'],
    accentDefault: 'charcoal',
  },

  // 3. Modern
  {
    id: 'modern-two-column',
    name: 'Modern Two-Column',
    category: 'Modern',
    filterCategory: 'modern',
    description: 'Classic Overleaf-style 2-column sidebar layout balancing technical skills & education with an expansive experience timeline.',
    atsFriendly: 'Parser optimized',
    recommendedLength: '1-2 Pages',
    layoutType: 'Two Column',
    bestFor: 'Software Engineers, Technical Product Managers, Design Technologists',
    tags: ['Modern', 'Two Column', 'Sidebar', 'Overleaf Style'],
    accentDefault: 'indigo',
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'Modern',
    filterCategory: 'modern',
    description: 'Contemporary typography with generous whitespace, subtle colored underlines, and clean visual flow.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Product Designers, Frontend Engineers, Tech Consultants',
    tags: ['Modern', 'Minimal', 'Indigo Accents', 'Contemporary'],
    accentDefault: 'indigo',
  },
  {
    id: 'clean-modern',
    name: 'Clean Modern',
    category: 'Modern',
    filterCategory: 'modern',
    description: 'Distinctive teal accent vertical bars on section headers with structured modern typography.',
    atsFriendly: 'Parser optimized',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Product Managers, UI/UX Technologists, Full-Stack Engineers',
    tags: ['Modern', 'Teal Accent', 'Left Border', 'Clean'],
    accentDefault: 'emerald',
  },
  {
    id: 'professional-modern',
    name: 'Professional Modern',
    category: 'Modern',
    filterCategory: 'modern',
    description: 'Two-column top header with contact pills, subtle divider rules, and refined typographic balance.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Data Analysts, Solutions Architects, Tech Leads',
    tags: ['Modern', 'Header Split', 'Refined', 'Professional'],
    accentDefault: 'navy',
  },
  {
    id: 'contemporary',
    name: 'Contemporary',
    category: 'Modern',
    filterCategory: 'modern',
    description: 'Warm charcoal tones with geometric typography, card dividers, and boxed skill chips.',
    atsFriendly: 'Parser optimized',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'Digital Media, Startups, Web3, Modern Enterprise',
    tags: ['Modern', 'Geometric', 'Contemporary', 'Card Accent'],
    accentDefault: 'charcoal',
  },

  // 4. Corporate
  {
    id: 'corporate-professional',
    name: 'Corporate Professional',
    category: 'Corporate',
    filterCategory: 'corporate',
    description: 'Authoritative dark banner header with crisp white contrast and structured enterprise sections.',
    atsFriendly: 'Parser optimized',
    recommendedLength: '1-2 Pages',
    layoutType: 'Header Split',
    bestFor: 'Enterprise Consulting, Management, Big Tech, Finance',
    tags: ['Corporate', 'Header Banner', 'Authoritative', 'Enterprise'],
    accentDefault: 'navy',
  },
  {
    id: 'corporate-executive',
    name: 'Corporate Executive',
    category: 'Corporate',
    filterCategory: 'corporate',
    description: 'Centered crest layout with deep burgundy accents, formal dates, and emphasis on executive trajectory.',
    atsFriendly: 'Standard compatible',
    recommendedLength: '1-2 Pages',
    layoutType: 'Single Column',
    bestFor: 'C-Suite, VP of Engineering, Operations Leads, Executive Search',
    tags: ['Corporate', 'Executive', 'Burgundy', 'Centered'],
    accentDefault: 'burgundy',
  },

  // 5. Academic
  {
    id: 'academic-research',
    name: 'Academic / Research',
    category: 'Academic',
    filterCategory: 'academic',
    description: 'Formal scholarly curriculum vitae layout highlighting Education, Publications, Research, and Teaching.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '2+ Pages',
    layoutType: 'Academic CV',
    bestFor: 'PhD Candidates, Researchers, University Lecturers, Data Scientists',
    tags: ['Academic', 'CV', 'Research', 'Publications', 'Formal Serif'],
    accentDefault: 'charcoal',
  },

  // 6. Compact
  {
    id: 'one-page-compact',
    name: 'One Page Compact',
    category: 'Compact',
    filterCategory: 'compact',
    description: 'Ultra-condensed micro line-height and tight margins engineered to fit everything cleanly on one page.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page Exactly',
    layoutType: 'Compact Single Column',
    bestFor: 'Single-page mandate applications, Quick career fairs, Tech meetups',
    tags: ['Compact', '1 Page', 'Dense', 'Space Saver'],
    accentDefault: 'slate',
  },
  {
    id: 'graduate-compact',
    name: 'Graduate Compact',
    category: 'Compact',
    filterCategory: 'compact',
    description: 'Optimized for campus placements and fresh graduates: Education, GPA, Coursework & Academic Projects upfront.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page',
    layoutType: 'Compact Single Column',
    bestFor: 'College Graduates, B.Tech / M.Tech Students, Campus Placements',
    tags: ['Compact', 'Graduate', 'College Placements', 'Education First'],
    accentDefault: 'navy',
  },
  {
    id: 'entry-level-professional',
    name: 'Entry-Level Professional',
    category: 'Compact',
    filterCategory: 'compact',
    description: 'Balanced layout tailored for 0-2 years of experience balancing foundation, hands-on projects, and skills.',
    atsFriendly: 'Highly compatible',
    recommendedLength: '1 Page',
    layoutType: 'Single Column',
    bestFor: 'Junior Developers, Associate Engineers, Career Switchers',
    tags: ['Compact', 'Entry Level', 'Junior Roles', 'Balanced'],
    accentDefault: 'emerald',
  },
];

// Default sample data used as fallback (now 100% fictional Alex Morgan, NEVER user personal details)
export const SAMPLE_RESUME_DATA: ResumeData = ALEX_MORGAN_PROFILE;

export { getSampleDataForTemplate, INITIAL_USER_RESUME_DATA };

export const getTemplateById = (id: string): ResumeTemplate => {
  return ALL_TEMPLATES.find((t) => t.id === id) || ALL_TEMPLATES[0];
};
